[package]
name = "exploit1"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = {version = "0.8.5", default-features = false}
rand_chacha = {version = "0.3.1", default-features = false}
reqwest = { version = "0.12.7", features = ["json"] }
serde = "1.0.210"
serde_derive = "1.0.210"
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
cityhasher = { version = "0.1.0", default-features = false }
aes = {version = "0.8.4", default-features = false}
cbc = {version = "0.1.2", features = ["alloc"], default-features = false}
cipher = {version = "0.4.4", features = ["block-padding"], default-features = false}
chrono = {version = "0.4.38"}
hex = {version = "0.4.3"}